/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.Scanner;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void PathFile(){
        File file = new File("/home/renad/Desktop/LTUCTraining/Advance/quotes/app/src/main/resources/qoutes.json");
        Quote q =new Quote(file);
        String str="/home/renad/Desktop/LTUCTraining/Advance/quotes/app/src/main/resources/qoutes.json";
        assertEquals(str,q.file.getPath());

    }

    @Test void ReadFile(){
        File file = new File("/home/renad/Desktop/LTUCTraining/Advance/quotes/app/src/main/resources/qoutes.json");
        Quote q = new Quote(file);
        try (Scanner sc = new Scanner(file)) {
            sc.nextLine();
            sc.nextLine();
            String Str = (String)sc.nextLine();
            assertEquals("    \"tags\": [",Str);
            }catch(Exception err){
            System.out.println(err.getMessage());
        }
    }

}
