/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
//import com.google.gson.Gson;

import com.google.gson.Gson;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {

        favqs q = new favqs();
        q.APIRead();


        
//        q.ReadFromAPI();
//        q.ReadGson();
////        q.print();
//        q.shuffleQoute();
//        System.out.println(q.length());
}
}



