/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;
//import com.google.gson.Gson;

import com.google.gson.Gson;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Quote q = new Quote();
        q.ReadGson();
//        q.print();
        q.shuffleQoute();
        System.out.println(q.length());

    }
}
